### ISSUE TITLE
Getting error "Error: Could not find or load main class"

### ISSUE THREAD

**Issue by Shabirmean** [rm5248/Java-RMI-Example#2]
When I try to run the code I get the following error:
**Error: Could not find or load main class com.rm5248.rmiserver.RMIServerMain**

I built the project with: **_mvn clean install_**
Then I ran the code using:

java -Djava.rmi.server.useCodebaseOnly=false -Djava.rmi.server.codebase=file:<PATH>/Java-RMI-Example/ com.rm5248.rmiserver.RMIServerMain

ANd I get the above error.
Please help

**Comment by rm5248** [comment]
If you're running it from the command line, what you probably have to do is to go to the maven 'target' directory and run the command from there, since it can't find the class.  I think that the `-Djava.rmi.server.codebase=file:/Java-RMI-Example/ ` is also wrong; you probably need it to be either `-Djava.rmi.server.codebase=file://./Java-RMI-Example/ ` or provide it an absolute path.
